app/routes/user.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from app.models import Usuario , DadosPessoais
from app import db
from datetime import datetime, date

user_bp = Blueprint('user', __name__, static_folder='static')

@user_bp.route('/login', methods=['GET','POST'])
def login():
    if request.method == "GET":
        return render_template('users/login.html')
    else:
        email = request.form['email']
        senha = request.form['password']
        dadosPessoais = DadosPessoais.query.filter_by(email=email).first()
        usuario = Usuario.query.filter_by(id_usuario=dadosPessoais.id_usuario).first()
        if email == dadosPessoais.email and senha == usuario.senha:
            session['id'] = usuario.id_usuario
            session['tipo'] = usuario.tipo
            session.permanent = True
            return redirect(url_for('main.index'))
        else:
            return redirect(url_for('user.login'))


@user_bp.route('/cadastro', methods=['GET','POST'])
def cadastro():
    if request.method == 'GET':
        return render_template('users/cadastro.html')
    else:
        novo_usuario = Usuario(
            nome = request.form['username'],
            senha = request.form['password'],
            tipo = 'cliente',
            status = 1
        )
        db.session.add(novo_usuario)
        db.session.commit()

        dados_pessoais = DadosPessoais(
            endereco = request.form['endereco'],
            email = request.form['email'],
            dataNascimento = datetime.strptime(request.form['dataNascimento'], '%Y-%m-%d'),
            rg = request.form['rg'],
            cpf = request.form['cpf'],
            telefone = request.form['telefone'],
            id_usuario = Usuario.query.filter_by(nome=request.form['username']).first().id_usuario
        )
        db.session.add(dados_pessoais)
        db.session.commit()

        return redirect(url_for('user.login'))
    
@user_bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('user.login'))

app/templates/users/cadastro.html
{% extends 'base.html' %}

{% block content %}
<main class="container">
    <section class="card">
        <h1>Cadastro</h1>
        <form action="{{url_for('user.cadastro')}}" method="post">
            <div class="form-input">
                <label for="username">Nome:</label>
                <input type="text" name="username" id="username" required>
            </div>
            <div class="form-input">
                <label for="email">E-mail:</label>
                <input type="email" name="email" id="email" required>
            </div>
            <div class="form-input">
                <label for="dataNascimento">Data de nascimento:</label>
                <input type="date" name="dataNascimento" id="dataNascimento" required>
            </div>
            <div class="form-input">
                <label for="rg">RG:</label>
                <input type="text" name="rg" id="rg" required>
            </div>
            <div class="form-input">
                <label for="cpf">CPF:</label>
                <input type="text" name="cpf" id="cpf" required>
            </div>
            <div class="form-input">
                <label for="telefone">Telefone:</label>
                <input type="text" name="telefone" id="telefone" required>
            </div>
            <div class="form-input">
                <label for="endereco">Endereço:</label>
                <input type="text" name="endereco" id="endereco" required>
            </div>
            
            <div class="form-input">
                <label for="password">Senha:</label>
                <input type="password" name="password" id="password" required>
            </div>
            <div class="form-input">
                <label for="confirmPassword">Confirmação de senha:</label>
                <input type="password" name="confirmPassword" id="confirmPassword" required>
            </div>
            <div class="form-input">
                <button type="submit">Cadastrar</button>
            </div>
        </form>
        <p>Já possue uma conta? <a href="{{url_for('user.login')}}">Entre na sua conta</a></p>
    </section>
</main>
{% endblock %}

app/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<main class="container">
    <section class="card">
        <h1>Login</h1>
        <form action="{{url_for('user.login')}}" method="post">
            <div class="form-input">
                <label for="email">E-mail:</label>
                <input type="email" name="email" id="email" required>
            </div>
            <div class="form-input">
                <label for="password">Senha:</label>
                <input type="password" name="password" id="password" required>
            </div>
            <div class="form-input">
                <button type="submit">Entrar</button>
            </div>
            {% if erro %}
            <p>{{erro}}</p>
            {% endif %}
        </form>
        <p>Não possue uma conta? <a
                href="{{url_for('user.cadastro')}}">Cadastre-se</a></p>
    </section>
</main>
{% endblock %}