app/routes/reserva.py
from flask import Blueprint, render_template, request, redirect, session, url_for, flash
from app.models import Reserva, Veiculo, Usuario
from app import db
from app.middlewares import AuthMiddleware
from datetime import datetime, date

reserva_bp = Blueprint('reserva', __name__, static_folder='static', template_folder='templates/reservas')

@reserva_bp.before_request
def loginAuth():
    if not AuthMiddleware.is_logged():
        return redirect(url_for('user.login'))

@reserva_bp.route('/reservas')
def reservas():
    if not AuthMiddleware.get_employee_permission(): return redirect(url_for('main.index'))
    reservas = Reserva.query.all()
    if len(reservas) < 1:
        flash('Nenhuma reserva encontrada')
        return render_template('reservas/reservas.html')
    veiculos = []
    usuarios = []
    for reserva in reservas:
        veiculos.append({
            'marca': Veiculo.query.filter_by(id_veiculo=reserva.id_veiculo).first().marca,
            'modelo': Veiculo.query.filter_by(id_veiculo=reserva.id_veiculo).first().modelo,
            'placa': Veiculo.query.filter_by(id_veiculo=reserva.id_veiculo).first().placa,
        })
        usuarios.append({
            'nome': Usuario.query.filter_by(id_usuario=reserva.id_usuario).first().nome,
        })
    return render_template('reservas/reservas.html', reservas=reservas, veiculos=veiculos, usuarios=usuarios)

@reserva_bp.route('/minhas_reservas')
def minhas_reservas():
    reservas = Reserva.query.filter_by(id_usuario=session['id'])
    if not reservas.first():
        flash('Você não possui reservas')
        return render_template('reservas/minhas_reservas.html')
    
    veiculos = []
    for reserva in reservas:
        veiculos.append({
            'marca': Veiculo.query.filter_by(id_veiculo=reserva.id_veiculo).first().marca,
            'modelo': Veiculo.query.filter_by(id_veiculo=reserva.id_veiculo).first().modelo,
            'placa': Veiculo.query.filter_by(id_veiculo=reserva.id_veiculo).first().placa,
        })
    return render_template('reservas/minhas_reservas.html', reservas=reservas , veiculos=veiculos)

@reserva_bp.route('/form/<int:id>')
def form(id):
    return render_template('reservas/cadastrar_reserva.html', veiculo=Veiculo.query.get(id))

@reserva_bp.route('/cadastro/<int:id>', methods=['POST'])
def cadastro(id):
    novaReserva = Reserva(
        id_veiculo=id,
        id_usuario=session['id'],
        dataInicio=datetime.strptime(request.form['dataInicial'], '%Y-%m-%d').date(),
        dataFim=datetime.strptime(request.form['dataFinal'], '%Y-%m-%d').date(),
        status=1
    )
    
    db.session.add(novaReserva)
    db.session.commit()
    
    return redirect(url_for('reserva.minhas_reservas'))

@reserva_bp.route('/cancelar/<int:id>')
def cancelar(id):
    reserva = Reserva.query.filter_by(id_reserva=id).first()
    db.session.delete(reserva)
    db.session.commit()
    return redirect(url_for('reserva.minhas_reservas'))

app/templates/reservas/cadastrar_reserva.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}
    <section id="content">
        <main id="main">
            <form class="form-reservas" method="post" action="{{url_for('reserva.cadastro', id=veiculo.id_veiculo)}}" enctype="multipart/form-data">
                <div id="formulario">
                    <h2>Modelo escolhido</h2>
                    <ul class="dados-veiculo">
                        <li>Marca: {{ veiculo.marca }}</li>
                        <li>Modelo: {{ veiculo.modelo }}</li>
                    </ul>
                    <h2>Reserva</h2>
                    <div class="blocoFormulario">
                        <label>Data inicial da reserva</label>
                        <input type="date" name="dataInicial" placeholder="Data inicial" class="inputBase" required>
                    </div>
                    <div class="blocoFormulario">
                        <label>Data final da reserva</label>
                        <input type="date" name="dataFinal" placeholder="Data final" class="inputBase" required>
                    </div>
                    <div class="blocoFormulario">
                        <button type="submit">Cadastrar</button>
                    </div>

                </div>
            </form>
        </main>
    </section>

{% endblock %}

app/templates/reservas/minhas_reservas.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}
<section id="content">
    <main id="main">
        <table border="1" class="tabela-reservas">
            <thead>
                <th>Carro reservado</th>
                <th>Data inicial</th>
                <th>Data final</th>
                <th>Status</th>
                <th colspan="2">Ações</th>
            </thead>
            <tbody>
                {% for reserva in reservas %}
                {% set veiculo = veiculos[loop.index0] %}
                <tr>
                    <td>
                        <ul>
                            <li>Marca: {{ veiculo['marca'] }}</li>
                            <li>Modelo: {{ veiculo['modelo'] }}</li>
                        </ul>
                    </td>
                    <td>{{reserva.dataInicio}}</td>
                    <td>{{reserva.dataFim}}</td>
                    <td>
                        {% if reserva.status == 1 %}
                        <p>Ativo</p>
                        {% else %}
                        <p>Cancelado</p>
                        {% endif %}
                    </td>
                    <td>
                        <a
                            href="{{url_for('reserva.cancelar', id=reserva.id_reserva)}}">Cancelar</a>
                    </td>
                </tr>
                {% endfor %}

                {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <tr>
                        <td colspan="6">
                            <ul>
                                {% for message in messages %}
                                <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </td>
                    </tr>
                {% endif %}
                {% endwith %}
            </tbody>
        </table>
    </main>

</section>

{% endblock %}

app/templates/reservas/reservas.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}
<section id="content">
    <main id="main">
        <table border="1" class="tabela-reservas">
            <thead>
                <th>Carro reservado</th>
                {% if session['tipo'] == 'funcionario' %}
                <th>Solicitante</th>
                {% endif %}
                <th>Data inicial</th>
                <th>Data final</th>
                <th>Status</th>
                <th colspan="2">Ações</th>
            </thead>
            <tbody>
                {% for reserva in reservas %}
                {% set veiculo = veiculos[loop.index0] %}
                <tr>
                    <td>
                        <ul>
                            <li>Marca: {{ veiculo['marca'] }}</li>
                            <li>Modelo: {{ veiculo['modelo'] }}</li>
                        </ul>
                    </td>
                    {% if session['tipo'] == 'funcionario' %}
                    {% set usuario = usuarios[loop.index0] %}
                    <td>
                        {{ usuario['nome'] }}
                    </td>
                    {% endif %}
                    <td>{{reserva.dataInicio}}</td>
                    <td>{{reserva.dataFim}}</td>
                    <td>
                        {% if reserva.status == 1 %}
                        <p>Ativo</p>
                        {% else %}
                        <p>Cancelado</p>
                        {% endif %}
                    </td>
                    <td>
                        <a
                            href="{{url_for('reserva.cancelar', id=reserva.id_reserva)}}">Cancelar</a>
                    </td>
                </tr>
                {% endfor %}
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                <tr>
                    <td colspan="6">
                        <ul>
                            {% for message in messages %}
                            <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                {% endif %}
                {% endwith %}
            </tbody>
        </table>
    </main>

</section>

{% endblock %}