app/routes/reserva.py
from flask import Blueprint, render_template, request, redirect, session, url_for, flash
from app.models import Reserva, Veiculo, Usuario
from app import db
from app.middlewares import AuthMiddleware
from datetime import datetime, date

reserva_bp = Blueprint('reserva', __name__, static_folder='static', template_folder='templates/reservas')

@reserva_bp.before_request
def loginAuth():
    if not AuthMiddleware.is_logged():
        return redirect(url_for('user.login'))

@reserva_bp.route('/reservas')
def reservas():
    if not AuthMiddleware.get_employee_permission(): return redirect(url_for('main.index'))
    reservas = Reserva.query.all()
    if len(reservas) < 1:
        flash('Nenhuma reserva encontrada')
        return render_template('reservas/reservas.html')
    veiculos = []
    usuarios = []
    for reserva in reservas:
        veiculos.append({
            'marca': Veiculo.query.filter_by(id_veiculo=reserva.id_veiculo).first().marca,
            'modelo': Veiculo.query.filter_by(id_veiculo=reserva.id_veiculo).first().modelo,
            'placa': Veiculo.query.filter_by(id_veiculo=reserva.id_veiculo).first().placa,
        })
        usuarios.append({
            'nome': Usuario.query.filter_by(id_usuario=reserva.id_usuario).first().nome,
        })
    return render_template('reservas/reservas.html', reservas=reservas, veiculos=veiculos, usuarios=usuarios)

@reserva_bp.route('/minhas_reservas')
def minhas_reservas():
    reservas = Reserva.query.filter_by(id_usuario=session['id'])
    if not reservas.first():
        flash('Você não possui reservas')
        return render_template('reservas/minhas_reservas.html')
    
    veiculos = []
    for reserva in reservas:
        veiculos.append({
            'marca': Veiculo.query.filter_by(id_veiculo=reserva.id_veiculo).first().marca,
            'modelo': Veiculo.query.filter_by(id_veiculo=reserva.id_veiculo).first().modelo,
            'placa': Veiculo.query.filter_by(id_veiculo=reserva.id_veiculo).first().placa,
        })
    return render_template('reservas/minhas_reservas.html', reservas=reservas , veiculos=veiculos)

@reserva_bp.route('/form/<int:id>')
def form(id):
    return render_template('reservas/cadastrar_reserva.html', veiculo=Veiculo.query.get(id))

@reserva_bp.route('/cadastro/<int:id>', methods=['POST'])
def cadastro(id):
    novaReserva = Reserva(
        id_veiculo=id,
        id_usuario=session['id'],
        dataInicio=datetime.strptime(request.form['dataInicial'], '%Y-%m-%d').date(),
        dataFim=datetime.strptime(request.form['dataFinal'], '%Y-%m-%d').date(),
        status=1
    )
    
    db.session.add(novaReserva)
    db.session.commit()
    
    return redirect(url_for('reserva.minhas_reservas'))

@reserva_bp.route('/cancelar/<int:id>')
def cancelar(id):
    reserva = Reserva.query.filter_by(id_reserva=id).first()
    db.session.delete(reserva)
    db.session.commit()
    return redirect(url_for('reserva.minhas_reservas'))

app/routes/veiculo.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from app.models import Veiculo, Reserva
from app import db
from app.middlewares import AuthMiddleware
from werkzeug.utils import secure_filename
import os

veiculo_bp = Blueprint('veiculo', __name__, static_folder='static')

@veiculo_bp.before_request
def loginAuth():
    if not AuthMiddleware.is_logged():
        return redirect(url_for('user.login'))

@veiculo_bp.route('/')
def index():
    veiculos = Veiculo.query.all()
    return render_template('veiculos/cards_veiculos.html', veiculos=veiculos)

@veiculo_bp.route('/adicionar_veiculo', methods=['GET','POST'])
def adicionar_veiculo():
    if request.method == 'POST':
        marca = request.form['marca']
        modelo = request.form['modelo']
        placa = request.form['placa']
        categoria = request.form['categoria']
        ano = int(request.form['ano'])
        valor = float(request.form['valor'].replace(',','.'))
        status = request.form['status']
        imagem = request.files['imagem']

        if AuthMiddleware.image_validation(imagem):
            imagemName = secure_filename(imagem.filename)
            imagem.save(f'app/static/carImages/{imagemName}')
        
            veiculo = Veiculo(marca=marca, modelo=modelo, placa=placa, categoria=categoria, ano=ano, precoDia=valor, imagem=imagemName, disponibilidade=status)
        
            db.session.add(veiculo)
            db.session.commit()
        
        return redirect('/veiculo')
    else:
        return render_template('veiculos/cadastro_veiculo.html')

@veiculo_bp.route('/deletar/<int:id>')
def deletar(id):
    if AuthMiddleware.get_employee_permission():
        veiculo = Veiculo.query.filter_by(id_veiculo=id).first()
        reservas = Reserva.query.filter_by(id_veiculo=veiculo.id_veiculo)
        
        db.session.delete(veiculo)
        for reserva in reservas:
            db.session.delete(reserva)
        db.session.commit()
        
        return redirect('/veiculo')
    else:
        return redirect('/veiculo')

@veiculo_bp.route('/editar/<int:id>', methods=['GET','POST'])
def editar_veiculo(id):
    if not AuthMiddleware.get_employee_permission():
        return redirect('/veiculo')
    veiculo = Veiculo.query.filter_by(id_veiculo=id).first()
    if request.method == 'GET':
        return render_template('veiculos/editar_veiculo.html', veiculo=veiculo)
    else:
        veiculo.marca = request.form['marca']
        veiculo.modelo = request.form['modelo']
        veiculo.placa = request.form['placa']
        veiculo.categoria = request.form['categoria']
        veiculo.ano = int(request.form['ano'])
        veiculo.precoDia = float(request.form['precoDia'].replace(',','.'))
        veiculo.status = request.form['status']
        if request.files['imagem']:
            for file in os.listdir('app/static/carImages'):
                if file == veiculo.imagem:
                    os.remove(f'app/static/carImages/{file}')
                    
            imagem = request.files['imagem']
            if AuthMiddleware.image_validation(imagem):
                imagemName = secure_filename(imagem.filename)
                imagem.save(f'app/static/carImages/{imagemName}')
                veiculo.imagem = imagem.filename
        else:
            veiculo.imagem = veiculo.imagem
        db.session.commit()
        return redirect('/veiculo')

app/templates/veiculos/cadastro_veiculo.html
{% extends './base.html' %}

{% block content %}
{% include 'navbar.html' %}
<section id="content">
    <main id="main">
        <section id="Veiculos">
            <h1>Formulário Cadastrar Veículos</h1>
            <section id="secaoFormulario">
                <form method="post" action="/veiculo/adicionar_veiculo" enctype="multipart/form-data">
                    <div id="formulario">
                        <div class="blocoFormulario">
                            <label>Marca</label>
                            <input type="text" name="marca"
                                placeholder="Nome veículo" class="inputBase" required>
                        </div>
                        <div class="blocoFormulario">
                            <label>Modelo</label>
                            <input type="text" name="modelo" placeholder="Modelo"
                                class="inputBase" required>
                        </div>
                        <div class="blocoFormulario">
                            <label>Placa</label>
                            <input type="text" name="placa" placeholder="Placa"
                                class="inputBase" required>
                        </div>
                        <div class="blocoFormulario">
                            <label>Categoria</label>
                            <input type="text" name="categoria" placeholder="Categoria"
                                class="inputBase" required>
                        </div>
                        <div class="blocoFormulario">
                            <label>Ano</label>
                            <input type="text" name="ano" placeholder="Ano"
                                class="inputBase" required>
                        </div>
                        <div class="blocoFormulario">
                            <label>Valor</label>
                            <input type="text" name="valor" placeholder="Valor"
                                class="inputBase" required>
                        </div>
                        <div class="blocoFormulario">
                            <label>Status</label>
                            <select class="inputBase" required name="status">
                                <option value="0">Inativado</option>
                                <option value="1" selected>Ativo</option>
                            </select>
                        </div>
                        <div class="blocoFormulario">
                            <label>Imagem</label>
                            <input type="file" name="imagem" required>
                        </div>

                        <div class="blocoFormulario">
                            <button type="submit">Cadastrar</button>
                        </div>

                    </div>
                </form>
            </section>
        </section>
    </main>
</section>
{% endblock %}

app/templates/veiculos/cards_veiculos.html
{% extends './base.html' %}

{% block content %}
{% include 'navbar.html' %}

<section id="content">
    <main id="main">
        <!-- veiculos -->
        <section id="Veiculos">
            <h1>Veículos Disponíveis</h1>
            <div class="listaVeiculos">
                {% for veiculo in veiculos %}
                    <div class="blocosVeiculos">
                        <img src="{{url_for('static', filename='carImages/')}}{{veiculo.imagem}}">
                        <div class="legenda">
                            <span class="nome">{{veiculo.marca}}</span>
                            <span class="preco">{{veiculo.precoDia}}</span>
                        </div>
                            <a class="btn-reservar" href="{{url_for('reserva.form', id=veiculo.id_veiculo)}}">Reservar</a>
                        {% if session['tipo'] == 'funcionario' %}
                            <div class="actions-group">
                                <a href="{{url_for('veiculo.editar_veiculo', id=veiculo.id_veiculo)}}"><img src="{{url_for('static', filename='imagens/edit.png')}}" alt="Botão editar"></a>
                                <a href="{{url_for('veiculo.deletar', id=veiculo.id_veiculo)}}"><img src="{{url_for('static', filename='imagens/trash.png')}}" alt="Botão editar"></a>
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </section>
    </main>
</section>

{% endblock %}

app/templates/veiculos/editar_veiculo.html
{% extends 'base.html' %}
{% block content %}
{% include 'navbar.html' %}

<section id="content">
    <main id="main">
        <form class="edit-form" action="{{url_for('veiculo.editar_veiculo', id=veiculo.id_veiculo)}}" method="POST" enctype="multipart/form-data">
            <div class="form-input">
                <label for="marca">Marca</label>
                <input type="text" name="marca" id="marca" value="{{veiculo.marca}}" required>
            </div>
            <div class="form-input">
                <label for="modelo">Modelo</label>
                <input type="text" name="modelo" id="modelo" value="{{veiculo.modelo}}" required>
            </div>
            <div class="form-input">
                <label for="placa">Placa</label>
                <input type="text" name="placa" id="placa" value="{{veiculo.placa}}" required>
            </div>
            <div class="form-input">
                <label for="categoria">Categoria</label>
                <input type="text" name="categoria" id="categoria" value="{{veiculo.categoria}}" required>
            </div>
            <div class="form-input">
                <label for="ano">Ano</label>
                <input type="number" name="ano" id="ano" value="{{veiculo.ano}}" required>
            </div>
            <div class="form-input">
                <label for="precoDia">Preço por dia</label>
                <input type="number" name="precoDia" id="precoDia" value="{{veiculo.precoDia}}" required>
            </div>
            <div class="form-input">
                <label for="imagem">Imagem</label>
                <input type="file" name="imagem" id="imagem">
            </div>
            <div class="form-input">
                <label for="status">Status</label>
                <select name="status" id="status">
                    <option value="1" {% if veiculo.status == 1 %} selected {% endif %}>Disponível</option>
                    <option value="0" {% if veiculo.status == 0 %} selected {% endif %}>Indisponível</option>
                </select>
            </div>
            <button type="submit">Atualizar</button>
        </form>
    </main>
</section>
{% endblock %}

app/templates/veiculos/index.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}
<section id="content">
    <main id="main">
        <!-- Home -->
        <section id="blocos">
            <div class="linha1">
                <div class="bl01 fundoVerde">
                    <img src="{{url_for('static', filename='imagens/icon.png')}}" width="76">
                    <h2>Nossos Veículos</h2>
                    <p>Lorem ipsum dolor sit amet consectetur
                        adipisicing elit. Architecto et fuga sequi, ex
                        eaque nesciunt perspiciatis quidem est mollitia,
                        iusto, odit molestias quibusdam voluptatum neque
                        ea? Laborum quia corporis aperiam!</p>

                </div>
                <div class="bl02 fundoPreto">
                    <img src="{{url_for('static', filename='imagens/icon.png')}}" width="76">
                    <h2 class="branco">Nossos Veículos</h2>
                    <p class="branco">Lorem ipsum dolor sit amet
                        consectetur adipisicing elit. Architecto et fuga
                        sequi, ex eaque nesciunt perspiciatis quidem est
                        mollitia, iusto, odit molestias quibusdam
                        voluptatum neque ea? Laborum quia corporis
                        aperiam!</p>

                </div>
                <div class="bl03 fundoAmarelo">
                    <img src="{{url_for('static', filename='imagens/icon.png')}}" width="76">
                    <h2>Nossos Veículos</h2>
                    <p>Lorem ipsum dolor sit amet consectetur
                        adipisicing elit. Architecto et fuga sequi, ex
                        eaque nesciunt perspiciatis quidem est mollitia,
                        iusto, odit molestias quibusdam voluptatum neque
                        ea? Laborum quia corporis aperiam!</p>

                </div>
            </div>
            <div class="linha2">

                <div class="blTexto">
                    <h1>Nossa História</h1>
                    <hr>
                    <p>Lorem ipsum dolor sit amet consectetur
                        adipisicing elit. Dolore excepturi, neque vero
                        quos id harum iusto recusandae quod repellat
                        quisquam ratione rem modi sint optio officiis
                        nulla. Reiciendis, dicta voluptates?
                        Lorem ipsum dolor sit amet consectetur
                        adipisicing elit. Dolore excepturi, neque vero
                        quos id harum iusto recusandae quod repellat
                        quisquam ratione rem modi sint optio officiis
                        nulla. Reiciendis, dicta voluptates?
                        Lorem ipsum dolor sit amet consectetur
                        adipisicing elit. Dolore excepturi, neque vero
                        quos id harum iusto recusandae quod repellat
                        quisquam ratione rem modi sint optio officiis
                        nulla. Reiciendis, dicta voluptates?
                        Lorem ipsum dolor sit amet consectetur
                        adipisicing elit. Dolore excepturi, neque vero
                        quos id harum iusto recusandae quod repellat
                        quisquam ratione rem modi sint optio officiis
                        nulla. Reiciendis, dicta voluptates?
                        Lorem ipsum dolor sit amet consectetur
                        adipisicing elit. Dolore excepturi, neque vero
                        quos id harum iusto recusandae quod repellat
                        quisquam ratione rem modi sint optio officiis
                        nulla. Reiciendis, dicta voluptates?

                    </p>
                </div>
                <div class="blImg"><img src="{{url_for('static', filename='imagens/image.png')}}"></div>
            </div>
        </section>
    </main>
</section>
{% endblock %}